# Generated by Django 4.2 on 2024-07-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
