# Generated by Django 4.2 on 2024-07-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='fullName',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
